version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
      - 8081:8081
      - 26657:26657
      - 26656:26656
    networks:
      - app-network
  pocket-core:
    image: poktnetwork/pocket-core:RC-0.4.0
    container_name: pocket-core
    privileged: true
    #command: "pocket start"
    #command: ["pocket", "start", "--seeds='b3d86cd8ab4aa0cb9861cb795d8d154e685a94cf@seed1.testnet.pokt.network:26656,17ca63e4ff7535a40512c550dd0267e519cafc1a@seed2.testnet.pokt.network:26656,f99386c6d7cd42a486c63ccd80f5fbea68759cd7@seed3.testnet.pokt.network:26656'"]
    command: "pocket version && tail -F dev/null"
    expose:
      - "8082" #  POKT RPC
      - "26657" #  Tendermint RPC
      - "26656" #  Tendermint Peers
    environment:
      # Your node's private key
      POCKET_CORE_KEY: "14e83883b88c54a56420ef4af0a6cfcf7ec992735341bbf0a70dcdd7444e5a675ad3c2acb46626b1c5e1283e26a966177b7c6f1e04a63e0350567529b42187c5"
      POCKET_CORE_PASSPHRASE: "yourpassphrase"
    volumes:
      - ./data:/root/.pocket
      # - "./chains.json:/home/app/.pocket/config/chains.json" #view tab for example file
      # - ./genesis.json:/root/.pocket/config/genesis.json
      # - "./config.json:/home/app/.pocket/config/config.json" # view tab for example file
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
